Text Area Max Length
mobi/goponents pull request #706
Opened 2020-10-30 18:40 UTC by StevenUlmer

## PR Checklist
Please check if your PR fulfills the following requirements:
- [x] The commit message follows our [guidelines](https://github.com/mobi/goponents/blob/master/CONTRIBUTING.md)
- [x] Tests for the changes have been added
- [x] Docs have been added or updated

## PR Type
What kind of change does this PR introduce?
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Style Update (CSS)
- [ ] Other... Please describe:

## What is the current behavior?
Resolves #705 

## What is the new behavior?
There is the ability to pass in a maxlength on the text area

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

2020-11-02 15:39 UTC, jaredami requested changes
Just noticed a typo but looks good otherwise 👍

2020-11-02 15:39 UTC, jaredami commented on projects/go-style-guide/src/app/features/ui-kit/components/form-docs/components/text-area-docs/text-area-docs.component.html
> +          The text area component's max legnth can be set via
Should "legnth" be "length"?

2020-11-02 19:07 UTC, grahamhency commented
@StevenUlmer, what if we also add on the `minlength` attribute to this? Probably not going to be used very often, but we're doing it in this PR as well #699

2020-11-09 17:50 UTC, grahamhency submitted a review, later dismissed
Looks good, thanks!

2020-11-09 18:25 UTC, jaredami requested changes
Couple of things in addition to my question about attribute vs property binding:

1. Should we add default values and add some logic to ensure that the `minlength` can't be set to greater than the `maxlength`, like what was done [here](https://github.com/mobi/goponents/pull/699#event-3975155105)?
2. Should we *technically* use brackets when setting the binding values since the inputs are of type `number` rather than `string`? Maybe not worth caring about...

2020-11-09 18:25 UTC, jaredami commented on projects/go-lib/src/lib/components/go-text-area/go-text-area.component.html
> +    [attr.minlength]="minlength || null"
One question I have about this is whether we should be using `attr.` for these. In the [Angular docs](https://angular.io/guide/binding-syntax) it says: "It is recommended that you set an element property with a property binding whenever possible."

Also [here](https://angular.io/guide/binding-syntax) it says "Attributes initialize DOM properties and then they are done. Property values can change; attribute values can't." I'm wondering if that means that when you use `attr.` it makes the binding static (i.e. it won't update if the value is changed)?

These two things make me think maybe we should just property binding here, unless the `text-area`s don't have these properties.

2020-12-02 19:21 UTC, grahamhency approved these changes

2020-12-02 19:21 UTC, merged