[Bug] Go-Table Change Selectable Issue
mobi/goponents pull request #776
Opened 2021-03-15 19:26 UTC by grahamhency

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our [guidelines](https://github.com/mobi/goponents/blob/master/CONTRIBUTING.md)
- [ ] Tests for the changes have been added
~~Docs have been added or updated~~

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Style Update (CSS)
- [ ] Other... Please describe:

## What is the current behavior?
See the issue referenced below for description of problem.
Resolves #774 

## What is the new behavior?
The table will handle when it becomes `selectable` after not being `selectable` and vice versa.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2021-03-16 15:37 UTC, StevenUlmer requested changes
Really the only concern here is around cleaning up the subscription on destroy. Could we also get a test around this change?

2021-03-16 15:37 UTC, StevenUlmer commented on projects/go-lib/src/lib/components/go-table/go-table.component.ts
> +  private selectionSubscriptions: Subscription = new Subscription();
I think everywhere else we've been adding a subject like `pageChange$` to track and remove subscriptions. Should we use the same here?

2021-03-16 15:37 UTC, StevenUlmer commented on projects/go-lib/src/lib/components/go-table/go-table.component.ts
> +  private selectionSubscriptions: Subscription = new Subscription();
Do we need to clean up this subscription in the `ngOnDestroy` method?

2021-03-18 15:39 UTC, grahamhency commented
@StevenUlmer I changed the approach up a bit to the `Subject` approach. I also added tests for this. Ready for another review.

2021-03-19 14:49 UTC, StevenUlmer approved these changes
Looks good. Thanks for adding the tests

2021-03-19 17:12 UTC, merged