[Bug] Issue #828 fix date validation
mobi/goponents pull request #830
Opened 2021-08-26 21:57 UTC by jaykravetz

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our [guidelines](https://github.com/mobi/goponents/blob/master/CONTRIBUTING.md)
- [x] Tests for the changes have been added
- [ ] Docs have been added or updated

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Style Update (CSS)
- [ ] Other... Please describe:

## What is the current behavior?

When picking a date (GoDatepickerComponent) in January, the field shows as invalid format

Resolves #828

## What is the new behavior?
The dates are validated using 0-11 for the months as described in the [MDN docs for `getMonth()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getMonth) 

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No
- [x] Maybe

The `LocaleFormat.validDate` function was changed.

2021-08-30 14:49 UTC, jaykravetz commented on projects/go-lib/src/lib/components/go-datepicker/locale-format.spec.ts
> +     */
We should have a test like this
```js
 describe('datePicked()', () => {
   it('should not validate dates with invalid args', () => {
     component.datePicked(new Date('cake'));
  
     fixture.detectChanges();
   
     console.log(component.control.value);
  });
});
```

The problem is that down the chain it calls `Intl.DateTimeFormat(locale).format(date);` which throws an error.

2021-08-30 18:15 UTC, grahamhency requested changes

2021-08-30 18:15 UTC, grahamhency commented on projects/go-lib/src/lib/components/go-datepicker/locale-format.spec.ts
> +     */
Per our conversation, I think this can be removed.

2021-08-31 03:18 UTC, grahamhency approved these changes

2021-08-31 13:59 UTC, merged